name: Scorecard

on:
  schedule:
    - cron: '17 6 * * 1'
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  scorecard:
    permissions:
      contents: read
      security-events: write
      id-token: write
      actions: read
    uses: szl-holdings/.github/.github/workflows/reusable-scorecard.yml@8186471f7f83f43f3aba4015fcfb2d322dcb4c83
